name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - 2.**

concurrency:
  group: release-${{ inputs.tag || github.ref_name }}
  cancel-in-progress: false

env:
  TODO: >-
    --deb-changelog 
  BUILD_TYPE: Release
  DEB_FPM_OPTS: >-
    --prefix '/'
    --config-files /etc/kvrocks/kvrocks.conf
    --config-files /etc/systemd/system/kvrocks.service.d/debian.conf
    --config-files /etc/logrotate.d/kvrocks
  COMMON_FPM_OPTS: >-
    -s dir
    -n kvrocks
    --verbose
    -a native
    --description 'A distributed key value NoSQL database that uses RocksDB as storage engine and is compatible with Redis protocol'
    --url 'https://kvrocks.apache.org'
    --license 'Apache-2.0'
    --conflicts redis
    --conflicts redis-server
    --provides redis
    --provides redis-server
    --after-install kvrocks.postinst
  SOFTWARE_NAME: 'kvrocks'

jobs:
  build_packages:
    name: Build DEB Package
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: ubuntu-22.04
            args_postfix_filename: 'u22'
            args_system: 'linux'
            args_architecture: 'amd64'
          - platform: ubuntu-24.04
            args_postfix_filename: 'u24'
            args_system: 'linux'
            args_architecture: 'amd64'
          - platform: ubuntu-26.04
            args_postfix_filename: 'u26'
            args_system: 'linux'
            args_architecture: 'amd64'
          - platform: ubuntu-24.04-arm
            args_postfix_filename: 'u24'
            args_system: 'linux'
            args_architecture: 'arm64'

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 64

      - name: Install Dependencies
        run: |
          sudo apt-get install -y git build-essential cmake libtool python3

      - name: Set env variables
        run: |
          echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV
          echo "ITERATION=$(cat ITERATION)" >> $GITHUB_ENV
          echo "PACKAGE_NAME=${{ env.SOFTWARE_NAME }}_$(cat VERSION)-$(cat ITERATION)_${{ matrix.args_system }}-${{ matrix.args_architecture }}-${{ matrix.args_postfix_filename }}.deb" >> $GITHUB_ENV

      - name: Tag version and push
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git tag "v${{ env.VERSION }}-${{ env.ITERATION }}" --force
          git push origin "v${{ env.VERSION }}-${{ env.ITERATION }}" --tag --force

      - name: Build
        run: |
          git clone -b "v${{ env.VERSION }}" https://github.com/apache/kvrocks.git
          cd kvrocks
          ./x.py build -DPORTABLE=1 -DCMAKE_BUILD_TYPE=Release -j $(nproc)

      - name: Make DEB release directory
        env:
          Build_Version: ${{ github.run_id }}.${{ github.run_number }}.${{ github.run_attempt }}
        run: |
          mkdir release
          mkdir release/etc
          mkdir release/etc/kvrocks/
          mkdir release/etc/logrotate.d
          mkdir release/etc/systemd
          mkdir release/etc/systemd/system
          mkdir release/etc/systemd/system/kvrocks.service.d
          mkdir release/lib
          mkdir release/lib/systemd
          mkdir release/lib/systemd/system
          mkdir release/usr
          mkdir release/usr/bin
          mkdir release/usr/share
          mkdir release/usr/share/kvrocks
          echo "."
          ls -ail .
          echo ".."
          ls -ail ..
          echo "kvrocks"
          ls -ail kvrocks
          echo "kvrocks/build"
          ls -ail kvrocks/build
          echo "kvrocks/build/bin"
          ls -ail kvrocks/build/bin
          echo "kvrocks/build/lib"
          ls -ail kvrocks/build/lib
          echo "release"
          ls -ail release
          ls -ailR release
          cp kvrocks/build/kvrocks release/usr/bin/
          cp kvrocks/build/kvrocks2redis release/usr/bin/
          cp kvrocks/kvrocks.conf release/etc/kvrocks/
          cp kvrocks.logrotate release/etc/logrotate.d/kvrocks
          cp -r kvrocks/LICENSE kvrocks/NOTICE kvrocks/licenses release/usr/share/kvrocks/
          cp kvrocks/utils/systemd/kvrocks.service release/lib/systemd/system/kvrocks-server.service
          sed -i 's/\/usr\/local\/bin\/kvrocks/\/usr\/bin\/kvrocks/' release/lib/systemd/system/kvrocks-server.service
          sed -i 's/kvrocks\.conf/kvrocks.conf --supervised systemd --daemonize no/' release/lib/systemd/system/kvrocks-server.service
          sed -iE 's/(# )?log\-dir .*$/log-dir \/var\/log\/kvrocks/' release/etc/kvrocks/kvrocks.conf
          cp systemd_debian.conf release/etc/systemd/system/kvrocks.service.d/debian.conf
          echo "{\"version\": \"${{ env.Build_Version }}\"}" > release/usr/share/kvrocks/build_version.json
          ls -ailR release

      - name: Package DEB
        continue-on-error: false
        uses: bpicode/github-action-fpm@v0.9.3
        with:
          fpm_args: '.'
          fpm_opts: '-t deb -v ${{ env.VERSION }} --iteration ${{ env.ITERATION }} -C release ${{ env.COMMON_FPM_OPTS }} ${{ env.DEB_FPM_OPTS }}'

      - name: Make DEB release directory
        run: |
          echo "SIMPLE_PACKAGE_NAME=$(ls *.deb | head -n 1)" >> $GITHUB_ENV
      
      - name: Rename package name
        run: |
          mv "./${{ env.SIMPLE_PACKAGE_NAME }}" "./${{ env.PACKAGE_NAME }}"

      - name: Upload built asset
        uses: actions/upload-artifact@v7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: ${{ env.PACKAGE_NAME }}
          path: ./${{ env.PACKAGE_NAME }}
          retention-days: 2

  release:
    runs-on: ubuntu-latest
    needs: build_packages
    steps:

      - uses: actions/checkout@v7
        with:
          fetch-depth: 64

      - name: Download all artifacts
        uses: actions/download-artifact@v8
        with:
          path: dist
          merge-multiple: true

      - name: Set env variables
        run: |
          echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV
          echo "ITERATION=$(cat ITERATION)" >> $GITHUB_ENV

      - name: List files
        run: |
          echo "local"
          ls -ail ./
          echo "dist"
          ls -ail dist
          ls -1 dist/${{ env.SOFTWARE_NAME }}_${{ env.VERSION }}-${{ env.ITERATION }}_*.deb

      - name: Prepare file list
        id: prep
        run: |
          echo "-1--"
          echo "$(ls -1 dist/${{ env.SOFTWARE_NAME }}_${{ env.VERSION }}-${{ env.ITERATION }}_*.deb )"
          echo "-2--"
          echo "$(ls -1 dist/${{ env.SOFTWARE_NAME }}_${{ env.VERSION }}-${{ env.ITERATION }}_*.deb | sed 's/dist\///' )"
          echo "-3--"
          echo "$(ls -1 dist/${{ env.SOFTWARE_NAME }}_${{ env.VERSION }}-${{ env.ITERATION }}_*.deb | sed 's/dist\///' | sed 's/ /\n/g')"
          echo "-4--"
          # files=$(ls -1 dist/${{ env.SOFTWARE_NAME }}_${{ env.VERSION }}-${{ env.ITERATION }}_*.deb | sed 's/dist\///' | sed 's/ /\n/g')
          # Convert spaces/newlines into newline-separated entries for the action
          # echo "files=$files" >> "$GITHUB_OUTPUT"
          echo "files=$(ls -1 dist/${{ env.SOFTWARE_NAME }}_${{ env.VERSION }}-${{ env.ITERATION }}_*.deb | sed 's/dist\///' | sed 's/ /\n/g')" >> "$GITHUB_OUTPUT"

      - name: List files
        run: |
          echo "${{ steps.prep.outputs.files }}"

      - name: Release
        continue-on-error: false
        uses: softprops/action-gh-release@v3
        with:
          tag_name: v${{ env.VERSION }}-${{ env.ITERATION }}
          name: ${{ env.VERSION }}-${{ env.ITERATION }}
          working_directory: dist
          files: ${{ steps.prep.outputs.files }}
          fail_on_unmatched_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Increment the value inside ITERATION
        continue-on-error: false
        run: |
          bash ./up_iteration.sh
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git commit -m "increment the ITERATION" ITERATION
          git push origin
